# https://wiki.hypr.land/Configuring/Variables/#input
input {
  kb_layout = us,sk
  kb_variant = ,qwerty
  kb_model =
  kb_options = caps:none, grp:alts_toggle
  kb_rules =

  numlock_by_default = true

  follow_mouse = 1

  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
  accel_profile = flat

  touchpad {
    natural_scroll = true 
    disable_while_typing = false
  }
  
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 4, horizontal, workspace

misc {
  mouse_move_enables_dpms = true
  key_press_enables_dpms = true
}
