windowrule {
  name = floating-window
  match:tag = floating-window

  float = true
  center = true
  size = 875 600
}

windowrule {
  name = add-floating-window-tag
  match:class = cfg.tui.*

  tag = +floating-window
}
