bindd = SUPER, C, Universal Copy, sendshortcut, CTRL, Insert,
bindd = SUPER, V, Universal Paste, sendshortcut, SHIFT, Insert,
bindd = SUPER, X, Universal cut, sendshortcut, CTRL, X,
bindd = SUPER CTRL, V, Clipbord History, exec, $menu -m clipboard 
