windowrule = float, tag:floating-window
windowrule = center, tag:floating-window
windowrule = size 875 600, tag:floating-window

windowrule = tag +floating-window, class:(mine.impala|mine.bluetui|mine.wiremix)
