windowrule {
  name = floating-window
  match:tag = floating-window

  float = on
  center = on
  size = 875 600
}

windowrule {
  name = add-floating-window-tag
  match:class = (org.custom.impala|linux.bluetui|linux.wiremix)

  tag = +floating-window
}
