exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

exec-once = waybar & hyprpaper & hypridle & hyprsunset & swayosd-server
exec-once = mako
exec-once = walker --gapplication-service

exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

exec-once = discord

exec-once = ~/.mybin/screen-time-watcher ~/Documents/screentime/$(date +%Y-%m-%d_%H-%M).txt
