source = ./bindings/clipboard.conf
source = ./bindings/tiling.conf
source = ./bindings/media.conf

bind = SUPER, Return, exec, $terminal +new-window
bind = SUPER, B, exec, zen-browser
bind = SUPER, E, exec, $fileManager -w
bind = SUPER, Space, exec, $menu

bindd = SUPER SHIFT, T, Task Manager, exec, xdg-terminal-exec -e btop +new-window

bind = SUPER, R, exec, ~/.config/waybar/scripts/launch.sh

bind = SUPER, Escape, exec, sh ~/.mybin/power-menu  


bindd = SUPER, PRINT, Select window to screenshot, exec, hyprshot -m window -o ~/Pictures/Screenshots
bindd = , PRINT, Select monitor to screenshot, exec, hyprshot -m output -o ~/Pictures/Screenshots
bindd = SUPER SHIFT, PRINT, Select region to screenshot, exec, hyprshot -m region -o ~/Pictures/Screenshots

bindd = SUPER, L, Locks the screen, exec, hyprlock
bind = SUPER SHIFT, L, exec, sleep 0.5 && hyprctl dispatch dpms off
