source = ./envs.conf
source = ./monitors.conf
source = ./input.conf
source = ./bindings.conf
source = ./autostart.conf
source = ./looknfeel.conf
source = ./windows.conf

source = ~/.config/hypr/conf.d/*.conf
