# Control Panels
bindd = SUPER CTRL, W, Launch Wifi Settings, exec, cfg-launch-tui impala
bindd = SUPER CTRL, A, Launch Audio Settings, exec, cfg-launch-tui wiremix
bindd = SUPER CTRL, B, Launch Bluetooth Settings, exec, cfg-launch-tui bluetui
bindd = SUPER CTRL, T, Launch Task Manager, exec, cfg-launch-tui btop

# Apps
bindd = SUPER, Return, Launch Terminal, exec, xdg-terminal-exec
bindd = SUPER, B, Launch Browser, exec, zen-browser
bindd = SUPER, E, Launch File Browser, exec, $fileManager

bindd = SUPER, Space, Launch App Menu, exec, $menu

bind = SUPER, Escape, exec, cfg-menu-system

# Captures
bindd = SUPER, PRINT, Select window to screenshot, exec, hyprshot -m window -o ~/Pictures/Screenshots
bindd = , PRINT, Select monitor to screenshot, exec, hyprshot -m output -o ~/Pictures/Screenshots
bindd = SUPER SHIFT, PRINT, Select region to screenshot, exec, hyprshot -m region -o ~/Pictures/Screenshots

bindd = SUPER CTRL, L, Locks the screen, exec, hyprlock
